version = "2.0"
watch_list = ["docs/**/*.md"]
hooks = ["quarto_attributes", "repl"]

[hook.repl.config.Lisp]
command = "scheme --eedisable --libdirs scheme"
first_prompt = "> "
change_prompt = '(waiter-prompt-string "{key}>")'
prompt = "{key}> "
