version = "2.0"
watch_list = ["docs/**/*.md"]
hooks = ["quarto_attributes", "repl"]

[hook.repl.config.Lisp]
command = "scheme --eedisable --libdirs scheme"
first_prompt = "> "
change_prompt = '(waiter-prompt-string "{key}>")'
prompt = "{key}> "

[hook.repl.config.Python]
command = "uv run python -q"
first_prompt = ">>>"
change_prompt = 'import sys; sys.ps1 = "{key}>>> "; sys.ps2 = "{key}+++ "'
prompt = "{key}>>> "
continuation_prompt = "{key}\\+\\+\\+ "
environment = { NO_COLOR = "1", PYTHON_BASIC_REPL = "1" }
